### PR TITLE
update 0.8W

### PR DESCRIPTION
**Pull request by duduama**

### CODE REVIEW

**Comment by mocram** [comment]
At first glance seems to be ok...

-png's seem to be 600px width, why? Are they not available bigger?
-svg would be better if saved as optimized svg

**Comment by duduama** [comment]
which is 600px?
how optimize SVG?

**Comment by charlesduco** [comment]
Svg's are okay for me. The png's are not fully transparent, I can see white pixels arround the edges on a black background.
I fixed the transparancy of the png's and merged this.

**Comment by mocram** [comment]
With the 600px comment I meant...

Whenever I see a lot of png supplied which all have the same dimensions, they are in most cases already modified/cropped, probably from another picon pack or whatever.
In most cases you'll be able to find higher resolution versions...but apparently "Are they not available bigger?" was too much of a question to get an answer for.

**Comment by duduama** [comment]
i'm sorry but I do not understand. Where can I find 600px? Logos are from LyngSat. Where to look for another source? Thanks

**Comment by mocram** [comment]
I'm sorry... please ignore what I said about 600px etc. It seems I was just too tired when I looked...
They are indeed not all 600px...

My apologies.

**Pull request merged**
