### PR TITLE
Romanian logos

### PR DESCRIPTION
**Pull request by Lexzie**
Please add these logos and links

### CODE REVIEW

**Comment by mcfly822** [comment]
@Lexzie can you make please the pull requests in one commit?
@mocram asked this earlier, and I agree, because it is easier to see the changes (which files changed, and what changed).
Thanks 😉

**Comment by AbuBaniaz** [comment]
He is uploading files using the interweb, not an application. You are limited in what you can do

**Comment by Lexzie** [comment]
Thanks @AbuBaniaz .
@mcfly822 : As long as I have not learned how to do that, this is the best I can. Also I got stuck on installing the Ubuntu-app on Windows and time is limited.
Otherwise I have to go back making issues again, instead of pull requests.

**Comment by Lexzie** [comment]
Oeps, it was not merged?

**Comment by mcfly822** [comment]
@Lexzie ok, no problem, I didn't know that you don't know the system.
I can help you in private. You can find me in linuxsat-support forum, under name 'mcfly82'.

**Comment by AbuBaniaz** [comment]
Is that really the logo for bollywood tv?

**Comment by Lexzie** [comment]
> Is that really the logo for bollywood tv?

Yes.
afbeelding
afbeelding
http://www.bollywoodtv.ro/program.html

**Pull request merged**
