### PR TITLE
Unitymedia additions/changes - try #2

### PR DESCRIPTION
**Pull request by tkurbad**
Hi again,

I just replaced my crappy png logos from the last pull request by svg files and added several missing entries to srindex. I also updated the srindex file according to Unitymedia's last channel shuffling(s).

Also, I tried to simplify the use of quotes in 1-build-servicelist.sh. The script works fine for me, but feel free to leave out this commit while pulling.

Best,
Torsten

### CODE REVIEW

**Comment by picons** [comment]
Let's go for try #3:

Leave the script alone, it doesn't fix anything, I can read it just fine.
Some svg images contain a base64 encode of the png image. Definately a no-no.

PR should be ready to go, so all I have to do is click the nice green button called "Merge pull request"

TIP: If you edit svg files yourself, save as normal svg instead of inkscape svg.

**Comment by tkurbad** [comment]
Well then, I don't have enough time to convert crappy logos of local channels to properly vectorized SVGs.
I'll just live with my fork of the repo for the time being.

**Comment by picons** [comment]
If there isn't an svg to be found you just take the best png you can find, but you're not going to put a png inside of an svg. A pig dressed as a princess is still a pig.

**Comment by tkurbad** [comment]
Couldn't you have said that earlier?

I collected pngs, were svgs where nor available.
I then tried to vectorize them using inkscape. Inkscape, however, can't handle "non-vectorizable" things like color-gradients or heavily anti-aliased edges very well, even if one tunes the bitmap vectorization parameters.
Thus, I used an online autotracer where inkscape failed, which from the looks of it produced correct results. 
I wasn't aware that it is possible to embed pngs in svgs, but that's obviously what the online "tracer" did.

Anyway, after the "conversion" I deleted the pngs. Thus, I'll have to rediscover all the sources I used and re-download the logos. I won't have time for that now, since I'm away all weekend. I'll probably get to it next week.

Btw.: To avoid try 4, I re-read your contribution guidelines and changed srindex to have the new entries on top, so we don't have to take this one step at a time...

**Comment by picons** [comment]
```
Btw.: To avoid try 4, I re-read your contribution guidelines and changed srindex to have the new entries on top, so we don't have to take this one step at a time...
```

That's why they are there.

**Pull request closed without merging**
