### PR TITLE
Tjormola/devel

### PR DESCRIPTION
**Pull request by tjormola**
Update picons with better compatibility with networks available in Finland

### CODE REVIEW

**Comment by mocram** [comment]
Why are you deleting so many logos and updating optimized svg's with the same svg+added inkscape junk, but hardly any visual difference?

**Comment by mocram** [comment]
Adding entries to the bottom of snp/srp-index is also a nono, unless you know the downsides.

**Comment by mocram** [comment]
If you fix the following issues, I'm more than happy to revisit this.

- Are you absolutely sure that the deleted logos are not being broadcasted anywhere in the world? Unused logos don't take up any space in the final picons, so....
- Are all reference to deleted logos removed from snp/srp-index?
- Do not update perfectly fine working svg files with visually almost indentical ones, especially when you are just adding Inkscape metadata
- Try to keep your entries to snp/srp-index at the top, unless you can confirm that you resolved all conflicts that could occur.

**Comment by tjormola** [comment]
- _Are you absolutely sure that the deleted logos are not being broadcasted anywhere in the world? Unused logos don't take up any space in the final picons, so...._
Yes I'm sure, the channels in question have been either decommissioned or rebranded with names and logos introduced in the later commits. I could drop the deletions if you wish of course, but no one in the world watching live TV would ever miss these logos though. For historical purposes these would remain in the Git history even if deleted from the HEAD of course so why not drop these?
- _Are all reference to deleted logos removed from snp/srp-index_
Yes, most of them were never introduced in the current repo and its snp/srp-index in the first place when you bootstrapped the current incarnation of the picons repo.
- _Do not update perfectly fine working svg files with visually almost indentical ones, especially when you are just adding Inkscape metadata_
I could revert these for sure if you wish. I just noticed that someone has made a great job of documenting these channels on Finnish Wikipedia with nice SVG logos included. I thought these versions would probably have better original colouring etc. than the existing ones so I just grabbed them as is. What's your opinion, should I just revert these for the new PR or use the newer ones as is or use the newer ones re-exported with Inkscape with the extra metadata removed?

- _Try to keep your entries to snp/srp-index at the top, unless you can confirm that you resolved all conflicts that could occur._
Missed this one. Will move to the top with the new PR.

**Comment by mocram** [comment]
If you also rollback the updating of visually indentical svg's it's good for me. Most likely they were added as optimized svg and overwriting them has no benefits, but could introduce problems with rsvg-convert.

**Pull request closed without merging**
