### PR TITLE
Added/updated Pro TV channels

### PR DESCRIPTION
**Pull request by mcfly822**
* Delete protvinternational.default.png

* Add files via upload

* Update snp-index

* Update srp-index

### CODE REVIEW

**Comment by mcfly822** [comment]
Something is wrong with these files. The generated picons are weird...
For example:
progold
protv

**Comment by AbuBaniaz** [comment]
You can see the problem if you open the files with GIMP. OK with Inkscape.

**Comment by mcfly822** [comment]
@AbuBaniaz No, not the source.
The generated (built) png's are wrong. What you can download from picons.eu. Please download 220x132 white pack for example. The protv.png, protvinternational.png, etc. (these files in this commit) are wrong. It is "ganz egal" which png viewer you use 😄

**Comment by AbuBaniaz** [comment]
The source logos have the problem. You wont see issue with Inkscape.

**Comment by mcfly822** [comment]
Yes, we talk the same thing, but your point of view from the source (svg), and mine is from the result (png).
Unfortunately it is no matter what program can open the file correctly while the final png's (what we use) are bad. Yeah, what you said, something is wrong with the source files.
I open an issue about this problem.

**Comment by mocram** [comment]
Export as optimized svg in inkscape and test if rsvg can render correct, is been said numerous times.

**Comment by mcfly822** [comment]
Ok, I will.

**Pull request merged**
