### PR TITLE
index changes

### PR DESCRIPTION
**Pull request by AbuBaniaz**

### CODE REVIEW

**Comment by AbuBaniaz** [comment]
Are you asking or stating?

If you are asking, the answer is that it is not against the rules. It is pointless addition.

Images with SNP code will look for picons with names in the following order:
Service Reference
SNP Name
SNP Name "-hd"

So in your example, it will look for 1_0_19_772a_2c1_600_e080000.png, then **"arenaspsort1hd.png"** then **"arenaspsort1.png"**

**Comment by AbuBaniaz** [comment]
Maybe we could add this logo?
```https://www.o2tv.cz/assets/images/tv-logos/original/arena-sport1-hd.png```

**Comment by mocram** [comment]
I'm going to have to disagree with you on this one @AbuBaniaz, this is not a Enigma2 only project. I don't think we need to cripple ourselves, because Enigma2 might "fix" certain problems.

**Comment by AbuBaniaz** [comment]
We added SNP to OpenVix. Someone on PLI suggested that the "hd" mod should be added, it was then added to OpenVix too. Other interested image teams then merged the changes too.

SNPicons was an E2 project. If other projects adopted it, then it is a logical assumption that they would have added the whole set of changes. Otherwise, I would assume they would continue doing what they did before SNP anyway.

```
https://github.com/OpenViX/enigma2/blob/master/lib/python/Components/Renderer/Picon.py#L92
```
```
https://github.com/OpenPLi/enigma2/blob/master/lib/python/Components/Renderer/Picon.py#L85
```
Instead of assuming, is there a way to check on the non-E2 projects? 
If we *need* to add them, we add them. If we don't need to, we don't.

**Comment by mocram** [comment]
@AbuBaniaz and everybody else, please ignore everything I said above.

`arenasport1hd=arenasport1`, in this case we are using an incorrect logo for Arena Sport 1 HD, so this is not allowed, OpenVIX will however fallback to arenasport1, temporarly until a correct link is available.

If the hd channel were to use the exact same logo as the non hd channel, it could be allowed in.

So @AbuBaniaz is right.

**Comment by duduama** [comment]
ok. thanks for the explanation

**Pull request merged**
