### PR TITLE
Hungarian Sport TV logos unifying

### PR DESCRIPTION
**Pull request by mcfly822**
I made 3 hungarian sports channels ("Sport TV") logos unified. The current logos looking so different...

The source file is 'sport2-duslelaslu.default.png', and I modified this logo for Sport 1 and Sport m.
The source file was also modified a little, some minor corrections.

If these variants are good for this project, please pull them. If I need something to modify, please let me know.

### CODE REVIEW

**Comment by charlesduco** [comment]
Seems acceptable, but I found better quality vector logos at https://www.swan.sk/domacnosti/pomoc-a-podpora/dokumenty
([Ponuka služieb SWAN MULTIMEDIA](https://www.swan.sk/media/content/Ponuka_sluzieb_platna_od_1_12_2016_ver2.pdf))

I will add the svg files in my next commit.

**Comment by mcfly822** [comment]
Okay, good!
So it is also possible to add the vector format for Sport 1 HD and Sport 2 HD.

**Comment by charlesduco** [comment]
Yes, but I had to install the font Myriad Pro Bold. I'll add the svg files in my next commit.

**Comment by mcfly822** [comment]
Great :+1:

**Pull request closed without merging**
