### PR TITLE
Stop linking all radio channels to stingraymusic

### PR DESCRIPTION
**Pull request by AbuBaniaz**

### CODE REVIEW

**Comment by charlesduco** [comment]
I still don't understand which problem you have with these stingray channels.
Please explain, cause these channels actually exist: https://en.wikipedia.org/wiki/Stingray_Music_International

**Comment by AbuBaniaz** [comment]
It is not a matter of the radios existing, but the logos associated with the channels. Is this correct?
classic rock

And this too?
vintage60

We generally do not associate services with provider names. If they correct, I was mistaken.

**Comment by charlesduco** [comment]
Classic Rock on Astra 2 is indeed wrong in this case, this should be https://absoluteradio.co.uk/classic-rock/
But Stingray Music has also a "Classic Rock" channel: http://music.stingray.com/en/channels/001/Classic-Rock
That's the problem with service name picons, you never get the right picon. Tomorrow someone opens a pull request with radio channels on german cable which conflicts with your service names on Astra 2.

I will merge this cause Astra 2 is a popular satellite for enigma2 boxes.

**Comment by mocram** [comment]
Let's just hope that the german fella will check the sats and overrides using a serviceref instead of a new snp entry at the top. :-)

Try to keep SAT > CABLE > ARIAL
                   POPULAR SAT > LESS POPULAR SAT

Meaning cable, arial and less popular sat should overrule using service reference.

**Pull request merged**
