### PR TITLE
MBC Masr and MBC Masr 2

### PR DESCRIPTION
**Pull request by Lexzie**
New logo: MBC Masr 2
New links.

### CODE REVIEW

**Comment by mocram** [comment]
@Lexzie I'm gonna let you deal with this one on your own. Good luck!

**Comment by Lexzie** [comment]
I resolved the conflicts, but looks like I don't have write access yet.

**Comment by mocram** [comment]
oops

**Comment by mocram** [comment]
accept invitation first

**Comment by Lexzie** [comment]
Found the invite! 😄

**Pull request merged**
