### PR TITLE
Replace Vouli Tileorasi logos

### PR DESCRIPTION
**Pull request by Lexzie**
Please accept these logos in much better quality.

### CODE REVIEW

**Comment by Lexzie** [comment]
3 commits? I guess something has gone wrong again... (GitHub is not easy... :(  )

**Comment by charlesduco** [comment]
Wrong transparency and unnecessary white space around the logos.

**Comment by mocram** [comment]
@Lexzie Are you using the online github interface to edit logos or what? Or what is the reason you have such difficulty with editing multiple files in one commit?

You should do...

1) Edit files on desktop
2) Create 1 commit with your edited files on desktop
3) Push local changes to GitHub, to your fork
4) Create PullRequest on github.com

**Comment by Lexzie** [comment]
I will do that, right now very little time due to volunteerwork.

**Pull request closed without merging**
