### PR TITLE
updated some channels

### PR DESCRIPTION
**Pull request by charlesduco**

### CODE REVIEW

**Comment by AbuBaniaz** [comment]
Please do not delete the UK cable references if they are from an area different to yours. "Ex CW" and "Telewest" areas are likely to be the same, but "Pure" regions will be different.

Many thanks

**Comment by charlesduco** [comment]
I didn't delete the UK cable references, but there was a superfluous space in front of every line. I only deleted these spaces to satisfy the format requirements.

**Comment by AbuBaniaz** [comment]
In which, please accept my apologies.

Many thanks for the correction.

**Comment by picons** [comment]
@charlesduco 

Good catch btw, I missed it.

Thanks

**Pull request merged**
