### PR TITLE
Update SRP index

### PR DESCRIPTION
**Pull request by AbuBaniaz**

### CODE REVIEW

**Comment by picons** [comment]
I'm going to merge this, but could you read the following link for next time. Otherwise it's going to get quite messy.
http://eli.thegreenplace.net/2014/02/19/squashing-github-pull-requests-into-a-single-commit

**Comment by picons** [comment]
I have a followup question... What exactly do you mean with "SRP will deal with them"?

**Comment by AbuBaniaz** [comment]
I had trashed using GIThub on the web and then re-forked. May have caused confusion when opening GITHub for windows.

Regarding your follow up question, we cant have two channel with identical names pointing to different picons. In such cases, we will have to use the conventional (SRP) ones.

**Comment by picons** [comment]
In snp-index only the entry at the top should be used, if all works as expected, so that shouldn't cause any harm.

If you mean the actual output ending on the box...
You can add an entry to snp-index similar to the ones in srp-index, to navigate around that particular problem.

I see you did not add those, but mentioned something about SRP, just to be clear, when building the snp version, nothing is used from srp-index.

My "vision" was to link as much channels via SNP in snp-index and a few SRP links also in snp-index, so that 1 package contains everything that is needed, not that we have to go merge packages......if you know what I mean.

**Comment by AbuBaniaz** [comment]
I share your vision of doing most via SNP and the few exceptions by SRP as well as one package

So far, I've only built a dirty SNP verison. I am tidying the SNP references up first to hopefully ensure we get as many done that way first. This will mean fewer entries in the SRP index and most importantly less maintenance.

**Comment by picons** [comment]
`This will mean fewer entries in the SRP index`

I think you misunderstand what I'm trying to say.

snp-index can contain:
```
2843_7FE_2_11A0000=tv/bbcparliament          <------notice the serviceref
100procentnl=radio/100procentnl
```

srp-index can only contain:
```
101B_7EF_2_11A0000=tv/skymoviesboxoffice-gbr
101_E_85_C00000=tv/skybundesligahd-deu
```

srp-index and snp-index are totally different and srp-index does not extend snp-index.

**Comment by AbuBaniaz** [comment]
Thanks for clarification.

**Pull request merged**
