### PR TITLE
Updated UK Syfy logo and deleted old. Updated snp and srp index.

### PR DESCRIPTION
**Pull request by TheLegoBatman**

### CODE REVIEW

**Comment by AbuBaniaz** [comment]
I am not keen on the yellow default logo. What you have as dark should be fine as default. Let's see what others say.

**Comment by TheLegoBatman** [comment]
I went for the default logo used by the channel to be used by default. If people prefer the dark as default I will get it changed.

**Comment by AbuBaniaz** [comment]
I checked on 5w, 19.2, 28.2 and UK cable, onscreen logo was not yellow.

**Comment by TheLegoBatman** [comment]
On screen logos are white a lot of times even if a different colour is used as default for the channel list . I went by the logo they use on the website, facebook and twitter etc. From the research seemed to be their default logo. Either way, if yellow is not the preferred I will change it.

**Comment by Lexzie** [comment]
I would prefer the yellow logo, at least for the `light` variant.
By the way: If you consult the websites German, UK, Spain, Portugal all have the same color, but the French use a light blue logo:
image

**Pull request closed without merging**
