### PR TITLE
N-tv logo update

### PR DESCRIPTION
**Pull request by Lexzie**
Please accept these changes as mentioned in Issue #116

### CODE REVIEW

**Comment by mocram** [comment]
Please read the guidelines. `ntvturkiye` is named incorrectly.

**Comment by Lexzie** [comment]
Why is ntvturkiye named incorrectly? It's the name of that station: https://www.lyngsat.com/tvchannels/tr/NTV-Turkiye.html

**Comment by charlesduco** [comment]
Did you build the logos yourself? I get a completely black ntvturkiye logo instead of blue and yellow.

**Comment by mocram** [comment]
We are not naming a tv station, but a logo. Nowhere in the logo do I see the words `turkiye`. What if Marokko or Egypt start broadcasting the same channel with modified programming, but the same logo and they call it Ntv North Africa... you see the problem? We gonna link NorthAfrica to turkiye...?

All of those rules weren't made up for the lolz. No, they came to be, because we ran accross similar problems.

It is not yet mentioned explicitely yet I think, but `Logo name can only contain words visible in logo`

**Comment by Lexzie** [comment]
No, the NTV Türkiye logo was found here:
http://cdn1-referandum.ntv.com.tr/Assets/dist/img/svg/ntv-logo.svg
Downloaded it, and for testing I exported it to png in Inkscape (because I don't know how to determine  whether a background is transparent or white in Inkscape), then opened the png in Paint.net and the background was transparent.
So I did not edit the logo, just renamed it.

I understand now what you want with the naming of the logos. It's your choice.
How do I rename it now?

**Comment by mcfly822** [comment]
@mocram 

> Logo name can only contain words visible in logo

So, what about these (for example)?
https://github.com/picons/picons-source/blob/master/build-source/logos/tv1000actioneast.default.png
https://github.com/picons/picons-source/blob/master/build-source/logos/investigationdiscoveryxtrahd.default.png
https://github.com/picons/picons-source/blob/master/build-source/logos/investigationdiscoveryxtra.default.png
https://github.com/picons/picons-source/blob/master/build-source/logos/discoveryhd.default.png
https://github.com/picons/picons-source/blob/master/build-source/logos/fashiontv.default.svg
https://github.com/picons/picons-source/blob/master/build-source/logos/discovery.default.png

**Comment by Lexzie** [comment]
I have cleared this pull request from the NTV Türkiye logo and links (maybe deal with that later).
I was just trying to be complete here, right now the Turkish channel shows the German logo )-: .
Can the (German) n-tv logo be accepted now?

**Comment by mocram** [comment]
@mcfly822 We should aim for a logo name that is a good mix between the channel name and the actual logo. Adding country specific naming can cause problems later down the road, as the past has proven.

I think in the past we had some MTV logo that was in a different color and was only used for MTV Germany I think, later the same logo was also being used for another country. So we had to link for example MTV France to the germany logo. Then I came up with country codes, but this made the problem even more obvious, so now we've got the random word...

What was the point of those examples you gave? To prove me wrong or to make clear you do not understand what I meant? :)

**Comment by mcfly822** [comment]
@mocram my aim was just to show some exception. I did not make attack, and nobody is wrong :)
I understand what you meant, but you see, there are some logos which don't fullfill the rule "_Logo name can only contain words visible in logo_" what you wrote.
It is clear now, thank you for the example.

**Comment by mocram** [comment]
That's why it isn't a rule, but even if it was, it would be stupid calling a logo `d.default.svg`.

Just keep in mind we are not going to name a logo `discoverygermany.default.svg` when the word germany is nowhere to be seen, eventhough the logo differs in appearance from the discovery uk one. Just the same as we are not going to name a logo `.......radio` if the word radio is not in the logo.

**Pull request closed without merging**
