### PR TITLE
PR to issue191

### PR DESCRIPTION
**Pull request by mcfly822**
* Update snp-index

* Update srp-index

* Add files via upload

#191

### CODE REVIEW

**Comment by AbuBaniaz** [comment]
Looks like this has an EOL issue too

**Comment by mcfly822** [comment]
@AbuBaniaz thanks for merging.
Sorry, what does the "EOL issue" mean?

**Comment by AbuBaniaz** [comment]
There was a post about it a few days ago. But the overall result is that the logos keep showing up as if they have been modified every time that sourcetree opens up.

image

**Comment by mcfly822** [comment]
Sorry, I don't know sourcetree. I upload everything via github website. Did I failed something?

**Comment by mocram** [comment]
God damnit, this has to stop, the builds have halted again.

**Comment by mocram** [comment]
Or not, ignore my comment for now....

**Comment by Lexzie** [comment]
If I copy-paste the text from svg-file of the snp/srp-index additions in Notepad is see:

afbeelding

So afbeelding (Carriage Return, Line Feed) while I guess it should be only afbeelding?
**Is that the problem?**
Is that also a problem in snp-/srp-index?

Unfortunately this is how Inkscape saves the files. can a setting in Inkscape change that?
Or do we need to open every svg after saving (as Optimized SVG) with f.e. Notescape to replace every afbeelding with afbeelding?

Can be done by Ctrl-H and then:
afbeelding


Making the <CR> and <LF> vidible:
afbeelding

**Comment by mocram** [comment]
So not mycuisine that caused an issue , but 
```
Updating 04ee82f..0f418b2
error: Your local changes to the following files would be overwritten by merge:
        build-source/logos/cnnturkradyo.default.svg
        build-source/logos/cnnturkradyo.light.svg
        build-source/logos/rtp4k.light.svg
Please, commit your changes or stash them before you can merge.
Aborting
```

@Lexzie This is a lot easier/faster to change line endings, but should not be required.
ine

**Comment by charlesduco** [comment]
I think this line endings problem only occurs when using the Github website to upload text files to this repository.

If you use a git application like Sourcetree, the line endings should be automatically converted from CRLF to LF.

**Comment by mcfly822** [comment]
@charlesduco thanks!
Last chance for this, now I install Sourcetree.

**Comment by Lexzie** [comment]
@mocram Thanks for that tip. I knew there was a option for that in Notepad++ but couldn't find it anymore.
Also found the default setting for this in Notepad++ and changed it to Unix.

Still I don't know if my contributions (also) have caused the line-endings problem?
When I open a svg (which has LF line endings, checked it in Notepad++) in Inkscape and save them (as Optimized SVG) and re-open that file in Notepad++ it has CRLF line endings...
So, that's not okay I think. Am I right?
How do you do that when saving an Optimized SVG?
Help me, I want to be sure I do it right.

I haven't used Sourcetree, but I haven't committed push requests anymore lately.
I only have committed issues, but when files are uploaded badly there, they might end up causing errors in the repository? Let me know if that is the case and what I must do to correct it.

**Comment by mocram** [comment]
Normally git should handle this on its own. I dont care what the line endings are inside an svg. The scripts and srp snp index should be unix lf. But somehow the online repository has line ending changes and when a local git pull is done, it sees a difference, but it thinks the change was local and there are uncommited changes...but I did not really look into it yet. But it would get completely mental to start changing the svg output from inkscap

**Pull request merged**
