### PR TITLE
Some more HRT logos

### PR DESCRIPTION
**Pull request by mcfly822**
Some more HRT logos and .index entries for tv & radio channels.
#228

### CODE REVIEW

**Comment by mcfly822** [comment]
Will someone merge this PR or shall I close then?

**Comment by AbuBaniaz** [comment]
I got confused with the comments in the issue. Apart from the conflict, is everything ready?

**Comment by mcfly822** [comment]
Yes, I think everything is ready, but I ask @Lexzie to confirm this.
I hope you can correct the conflict.
Thanks @AbuBaniaz , and Merry Christmas for you and every conributors! :-)

**Comment by Lexzie** [comment]
Because of family visiting for Christmas I do not have time right now to check, but I'm sure it's alright.
But at least I want to wish you all a Merry Christmas!

**Comment by Lexzie** [comment]
All is okay, thanks everyone for your efforts.

@mcfly822 @AbuBaniaz @mocram and all others:
Hope you all had/have nice holidays and wish you a wonderful New Year's Eve and all the best for 2018!

**Comment by mocram** [comment]
The same to you and others. Happy new year.

**Pull request merged**
