### PR TITLE
Add logo for Scout FM

### PR DESCRIPTION
**Pull request by Lexzie**

### CODE REVIEW

**Comment by charlesduco** [comment]
Logos are okay, but please create a new pull request with only one commit please.

**Comment by AbuBaniaz** [comment]
Squashed and merged

https://github.com/blog/2141-squash-your-commits

**Comment by Lexzie** [comment]
Thanks for accepting the new logo.

**Comment by mocram** [comment]
@charlesduco I wouldn't have called them okay... but since they are in know... also don't really see the point of the light version with such minimal change

**Comment by Lexzie** [comment]
The default version has black outer edges, in the light version I made the outer edge white and the inner edge black.
This is also done because of your own rules here.

**Comment by mocram** [comment]
Don't have to explain me what you did, I can see that.

Although what you did is correct, nothing really wrong with that, but I'd rather have seen the time invested on cleaning up the logo, instead of flipping some colors. Just a tip.

scoutfm default

**Comment by Lexzie** [comment]
Thank you for this information

**Pull request merged**
