### PR TITLE
New SRP entries for Borders area IDs

### PR DESCRIPTION
**Pull request by masticman**
Inserted new entries to SRP-Index for BBC1, BBC2, ITV for Cumbria & SW Scotland Borders IDs.

Hi, Please note I'm absolutely brand new to GitHub and contributing to this project, so still finding my way with the processes.  If I've not followed correctly then please advise and I'll correct my ways, thanks.

### CODE REVIEW

**Comment by masticman** [comment]
Hi,

I've amended accordingly in 2nd commit, thanks for your feedback.  Let me know if I need to make a new pull request.  (sorry if this is a daft question, GitHub is a steep learning curve).

**Comment by AbuBaniaz** [comment]
Changes have been merged.

Any changes you make in a branch that has been used to make a pull request will always tag along to the pull request.

**Comment by mocram** [comment]
@abubaniaz 
Sigh, why would you merge this, it still has mistakes in it!

**Comment by AbuBaniaz** [comment]
Well spotted @mocram 
I missed the uppercase.

**Pull request merged**
