### PR TITLE
Improving logos

### PR DESCRIPTION
**Pull request by mcfly822**
Hello,
I started to improve the logo database to make the logos better and to reduce the database size.
I searched the existing logos in svg, or (in most cases) made them by myself. If this was not achieveable, I searched/made better resolution png's.
I checked the images with this repo's build script (rsvg). I did not found any error.
@charlesduco please check the images (and the naming) if you have time, my aim is improve the database not to make errors. I tried my best.

### CODE REVIEW

**Comment by mocram** [comment]
You are removing some logos which are still being used, without adding a replacement svg.

**Comment by AbuBaniaz** [comment]
@mocram, is there a list of the "missing logos"

**Comment by mocram** [comment]
```
build-source/logos/digianimalworld.default.png
build-source/logos/digianimalworld.light.png
build-source/logos/discoverychannel.default.png
build-source/logos/discoverychannel.light.png
build-source/logos/discoveryhistory.default.png
build-source/logos/discoveryworld.default.png
build-source/logos/discoveryworld.light.png
build-source/logos/drama-clivebesle.default.png
build-source/logos/sat7.default.png
build-source/logos/sat7.light.png
build-source/logos/sexysattv.default.png
```

**Comment by mcfly822** [comment]
These logos are not removed, just changed to another (better resolution) png's. I cannot draw them to svg, because the texture or colür gradient.
Did I failed something? I did not want to remove, just change. Do you see I removed? I see that I changed them.

**Comment by mocram** [comment]
Shit, do I feel stupid now.

I was so used of seeing a deleted png and an svg being added, that I just assumed you deleted them, but did not notice you were actually changing the svg, because github did not render the diff.

Doh!

**Comment by mocram** [comment]
digianimalworld.light.png looks like crap tho....

**Comment by mcfly822** [comment]
Thanks for merging!
What part looks like crap? The word 'DIGI'? The light version is the color inverse of the default, so in dark background looks much better. I'll try to improve the quality, but I think it is now better than the previous. Sure, not perfect :-)

**Comment by mocram** [comment]
Just looked at the logo on a black background, it's good enough, you can leave it as is.

**Comment by mcfly822** [comment]
Ok, thanks.

**Pull request merged**
