### PR TITLE
update snp-index and add picons

### PR DESCRIPTION
**Pull request by AbuBaniaz**

### CODE REVIEW

**Comment by picons** [comment]
Sorry Abu, but this contains too many mistakes, lots of white version logos in the regular logo location.
What's up with tv/alazeeraenglishhd, the name is spelled wrong, why the need to differentiate between the regular aljazeera logo and there's no link to be found for tv/alazeeraenglishhd

**Comment by AbuBaniaz** [comment]
Getting caught up between deleting by copy and re-forking from yours. I useGithub for windows, almost all the guides are for linux and comamnd line. There are no user friendly guides on how to import from main branch without losing local changes. This is why that error for spelling exists. I fixed it, and forgot to remove it out from file that I was using after having trashed and rebuilt. I am trashing/forjking to keep with changes.

I honestly don't know how to tell the differnce between white picons and normal ones. I made the same "error" a few months back (filename too). When you double click the image, it shows up the same as normal picture.

Anyway, we have to move forwards. We have the BT/ESPN  graphics missing.  I will upload them to WOS to save you having to rename etc. Please commit the ones that are acceptable. I got them from http://mediaportal-uk-logos.googlecode.com/svn/trunk/TV/Simple/

**Comment by picons** [comment]
If you press sync in GitHub Desktop, doesn't it just pull in the changes upstream? I just wouldn't make any commits before you are 100% synced, then create commit/PR.

I'm going to have a play with this myself to fully understand what would be a good way to deal with all this from GitHub Desktop......

A white logo, is mostly white and looks good on a dark background, a black picon is mostly black/dark and looks good on a white background. But if the logo is indeed like it is very white on its own by default, it's not the end of the world if it's put in just the tv/ folder. There were just quite few of them, so I thaught you might have made a mistake.

**Comment by picons** [comment]
I think it's best that you create a new branch, do your work create pull request, wait till I merge, delete your branch and update your master. Rinse repeat. That way you don't lose any changes in your branch and you can update the master branch any time without polluting it with your own commits.

**Comment by AbuBaniaz** [comment]
To compound the issue, just checked the copy on my desktop, the mis-spelt Aljazeera English HD is not there. So not sure where it got caught up.

You cant add images easily directy uisng the web version, otherwise that would have been ideal.

**Comment by picons** [comment]
Stop updating this, I'm also doing it.

**Comment by AbuBaniaz** [comment]
Thanks.

**Comment by picons** [comment]
It's merged in, I can actually open a pull request from you inside GitHub Desktop, which creates a new branch on my local PC, which I can freely modify as I like and create another pull request from that. As you can see in the last PR.

I think "branches" is the keyword here, you shouldn't need to fork/refork/delete/clone/etc.....

**Comment by picons** [comment]
Here's an interesting post about how to delete branches after your PR has been merged
http://www.fizerkhan.com/blog/posts/Clean-up-your-local-branches-after-merge-and-delete-in-GitHub.html

**Pull request closed without merging**
