### PR TITLE
Logos for Eutelsat 9A

### PR DESCRIPTION
**Pull request by Lexzie**
Few errors corrected.
Lots of logos added.
Guys, I've been working on this for a few days now and put a lot of effort in it.
If there are still some faults in it, please tell me so I can correct it.

### CODE REVIEW

**Comment by charlesduco** [comment]
Read the [contributing rules](https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md) again and check all logos again, especially the following rules:
- Background should be transparent.
- No empty space around the logo.

Transparent means for example:
- no ugly black pixels around a completely white logo.

Please build your commits also on your local machine to make sure all submitted svg files render correct: [Building the picons](https://github.com/picons/picons-source#building-the-picons)

**Comment by mocram** [comment]
Any plans to correct the mistakes in this PR? Or should we close it?

**Comment by mcfly822** [comment]
@mocram I can correct the bad logos (if no one would like to do it).

**Comment by Lexzie** [comment]
First of all I should figure out what I'm doing wrong. (I have read the rules!)
Second I had other business.
Third my laptop crashed, got a new one just yesterday.

So, yes I would like to correct the mistakes.
Still some questions:
-How do I know which logos are not okay if no-one says which ones??
-If mcfly822 wants to correct the errors please do so, but I'd like to know how you did it please.

**Comment by mcfly822** [comment]
@Lexzie Ok, you want to learn the picon "business", this is very good! I am learning also :smile: 
First, read charlesduco's advices again:

> Read the contributing rules again and check all logos again, especially the following rules:
**Background should be transparent.
No empty space around the logo.
no ugly remaining black pixels around a completely white logo.**

So, you should follow these instructions.
For example, I signed the errors in your ebsplus.default.png with red circle:
ebsplus default

This is unacceptable. And the resolution is also low. If I started to contribute this logo, I would do this steps:

1. search a good resouliton logo in google. A hi-res png or an svg. If I found, good.
2. If not found, I try to make the logo in svg format. Inkscape is very good for this. To learn inkscape, this forum is very very little. There are tons of books, wesites, forums and videos about vector-based images making, or you can learn by yourself it, as I did :smiley: 
3. If it is very hard to make the svg (for me, it is very hard to do images with color gradient), the better choice is png. So try again to find the logo in PNG (the channel's own website, own faceb*, twitt*, etc.).
4. JPG format, and make it transparent with GIMP.

Also take care of naming: the attached file should be (IMHO) ebsplus.light.png, because it is good for dark background. (See https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md )

The most important, is that the final result must be nice and and a result of a _demanding work_ :+1:

**Comment by Lexzie** [comment]
Thanks for pointing this out.

-I always make the background transparent, some logos are default totally non-transparent besides the outline. It's how the broadcaster intended the logo. I mean f.e. if they intended to have black or white letters inside the logo, it should remain so and not transparent.
Examples: 4e, Aigaio TV, Athanvan TV, C-music TV, ORTM, TFM.
-Empty space: I beleive I always cut back the logo.
-I saw that indeed some logos have remaining pixels due to converting them, f.e. black on transparent background to white or the other way round. Have to figure out to fix that or otherwise not submitting those logos.

1. I really try to find logos in svg-format, f.e. by using filetype:svg in the search command in google. Any tips are very welcome.
2. Making a logo myself will never resemble the original logo I beleive.
3. If I can't find svg-files I always use png. Indeed on website, facebook, twitter etc.
4. I use paint.net for png and Inkscape for svg

Naming: The white logo is the logo intended by the station, so that's why it's named ebsplus.default.png.
Because it cannot be displayed on a light background I convert the white to black and name that one ebsplus.dark.png because it's not the default!
If I'm wrong about this, please tell me. (Personaly I don't care about the dark logo because I only use light on transparent but I want to submit both.

I will review all logos, a lot of them are okay, but also a lot are not.
If you want to fix a logo that would be great but tell me, so we don't work on the same logo.

**Comment by mcfly822** [comment]
@Lexzie 
First, about the naming: maybe you are right, I am not sure about this.

The logos: here is an example, Duna World Rádió. See the difference between your version and my version. Yours edges are rough,  and not anti-aliased. There are ugly pixels somewhere at the edges. See in full resolution and you can see the differences (attached).
[dunaworldradio.zip](https://github.com/picons/picons-source/files/1367255/dunaworldradio.zip)

I have no time yet to completely check all of your logos. But I have the following hungarian radios: **Kossuth, Petőfi, Bartók, Dankó, Duna World**, so you do not need to correct these,

I think this is your PR (pull request), so you can correct the logos. But if you are stucked with some, I'm here and I will help you ;)

**Comment by Lexzie** [comment]
Okay, what is the best way to go?
Fixing, replacing, deleting logos in this pull request?
Because this pull request is quite large I'd rather close this one and start over.

**Comment by AbuBaniaz** [comment]
>I'd rather close this one and start over.

I'll close the pull request for you

**Comment by Lexzie** [comment]
@mcfly822 Can you please tell me how you managed to improve those logos?
I can't send you a personal message and don't know if you can send me one?
Do you want to make a pull request for the missing Hungarian logos?

**Comment by mcfly822** [comment]
@Lexzie I think there is no option to private message here in github. As far as I know :)

I found these logos on the web, and I made the 'light' version with GIMP.
I can adjust the mission hungarian logos also of course.

**Comment by mocram** [comment]
Regarding the naming of the ebsplus logo, my first instinct was to call him out on the fact it was named incorrect. HOWEVER, if the white/light logo is used by default as is by the broadcaster on their tv programming or website, it would have been named correctly.

Most logos found are made to look good on white, paper/website/tv, so the default(=original) version has to be this one. An exemption could be made for the ebsplus logo, but in the end, the picons should come out OK regardless.

**Comment by mocram** [comment]
arttv.light is also not upto snuff I you ask me.

**Comment by Lexzie** [comment]
Regarding the quality of the logos: Working on it. Takes a long time, so that's why I closed this pull request.

**Comment by mocram** [comment]
If you are modifying transparency with GIMP, try playing with `Colors > Color to Alpha` and `Selection > Shrink/Expand`.

Nobody will notice a lost 1px border, but everybody will see white pixels that shouldn't be there.

**Comment by Lexzie** [comment]
I have used Paint.net.
I used GIMP in the past and found it very difficult, but I guess GIMP will have better results?

**Comment by mocram** [comment]
gimp is a lot more powerfull, a bit like Word vs Notepad

**Comment by Lexzie** [comment]
Gonna take some time to get to know it, but I'm sure going to give it a try!
Thanks!

**Comment by Lexzie** [comment]
I have used your tips in GIMP, changing black to white and it works perfectly. Thanks for the help!
Result can be seen in Issue #147. As far as I can see no remaining pixels any-more.

**Pull request closed without merging**
