### PR TITLE
Wrong Discovery Science index

### PR DESCRIPTION
**Pull request by Lexzie**
Somebody changed all snp-indexes for Discovery Science, while it was clearly said that not all channels had the new logo.
(https://github.com/picons/picons-source/issues/123#issuecomment-336429383)

Almost all the channels with the (full) name Discovery Channel (HD) still have the "old" logo, as far as I can see.
These are all Discovery Science Europe.
The only exeptions to this rule are the SD versions of Discovery Science Türkiye on 7.0E and Polska on 13.0E.
Channels that have changed logo are the specific country versions UK, Italia and Polska.

Also added a lot missing links in both snp- and srp-index.

### CODE REVIEW

**Comment by AbuBaniaz** [comment]
This won't be merged. It is the correct one.
discovery science

**Comment by Lexzie** [comment]
Read my description and you'll see that we're both right and if you see the changes I've made you'll see that your channel will keep the new logo.
Or do I also have to show you screenshots with the old logo?

**Comment by AbuBaniaz** [comment]
You are still wanting to add this `discoveryscience=discoveryscience`

Can you please get the notion that logo name must equal dvb name out of your head.

**Comment by Lexzie** [comment]
> You are still wanting to add this discoveryscience=discoveryscience
> 
> Can you please get the notion that logo name must equal dvb name out of your head.

That's not why I did that. Please read my first comment.

**Comment by AbuBaniaz** [comment]
Why you did it and what you are doing are two different things.

I have manually added the SRP references. I will be renaming the science logos. They are still discovery science logos, just a different type. As was mentioned before, we link names/references to logos, not logos to names.

Please do not submit a pull request until I have done it.

**Comment by Lexzie** [comment]
No, no, no!
Don't rename the logos!!!
Keep both logos, they are both needed!

**Comment by mocram** [comment]
@Lexzie Please read https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md
Please listen to @AbuBaniaz

**Comment by AbuBaniaz** [comment]
Logos have been renamed. Both are present.  Use the desired version in the links. 

If an SNP name linking to one logo is already present, please use the service reference. SNP was coded  to allow this distinction.

**Comment by mocram** [comment]
@AbuBaniaz Why was this thread locked?

**Comment by AbuBaniaz** [comment]
Because the pointless debate will go on.

We have both logos on our reppsitory. Picons can be made with either. Instead of linking to desired logo, debate will ramble on pointlessly.

**Comment by mocram** [comment]
OK, unrelated to the above, but, I would like to ask you that if in the future there are strong worded comments directed at me, to not delete them. Just ping me and I will react accordingly. I know some people can get frustrated if they are told something they don't like to hear.

I gave you write permission to make commits directly to the repo, not to moderate the hell out of it, leaving me clueless about what's going on.

Hope you understand.

**Comment by AbuBaniaz** [comment]
OK                  .

**Pull request closed without merging**
