### PR TITLE
Fixing snp-links for NPO 1 Extra

### PR DESCRIPTION
**Pull request by Lexzie**
See last comment in Issue #352

### CODE REVIEW

**Comment by AbuBaniaz** [comment]
I have added here
https://github.com/picons/picons-source/commit/5557cec093a41a6dc5736950bd0d78a8a7b537d1

**Comment by Lexzie** [comment]
> Some logos are not really good, there are a lot of metadata inside the svg.

Logos were added before, not part of this PR.
See issue #352 
You made the `npo1extra`, `npo2extra` and `npo3extra` svg's, I just combined the existing `npozappxtra` svg with your `npo1extra`.
Do we need to clean up the metatags?

**Comment by mcfly822** [comment]
Yes, but when you save a file in inkscape, save az optimized svg, without metadata.
mocram-svgout1
mocram-svgout2
mocram-svgout3

For me it is no problem, but maybe charlesduco or mocram will clean this 😃

**Comment by charlesduco** [comment]
Just one consideration:
If you don't save as _optimized svg_ and you don't build the picons, you're never really sure if your newly added svg's will render correctly.

**Comment by Lexzie** [comment]
@mcfly822 I always save them as optimized svg without metadata.
@charlesduco About building the picons (if you mean building a ipk?) we have talked about that before.
It may be easy for you, for me takes time to learn how to do that.

**Pull request closed without merging**
