### PR TITLE
Added/updated Nordic SVGs

### PR DESCRIPTION
**Pull request by McLalala**

### CODE REVIEW

**Comment by mocram** [comment]
Why the need for changing tv6? What's up with th strange aspect ratio doc size? Try to make the default svg size big enough so whe at least can see the logo....

**Comment by McLalala** [comment]
The black and red colors differ. The source is Viasat Press website. https://s-module.se/_demo/viasat-toolkit/logotyper/logotyper

**Comment by charlesduco** [comment]
Please fix viewbox and resolution of the logos. Logos should be readable by human eyes on Github.
Please combine all changes for Nordic Viasat in one pull request.

**Comment by AbuBaniaz** [comment]
If you create a pull request from a branch, any subsequent changes you make in that branch will also get included. We had about 100 e-mails from your commits.

Any work you do should be in a different branch. When you are ready, create a pull request from your working branch. Once it is merged, you can delete the working branch.

**Comment by McLalala** [comment]
Oh, I'm sorry for all the changes! I'll get everything fixed in a new pull request. Thanks a lot for the heads up, and great work on the project as well. :)

**Pull request closed without merging**
