### PR TITLE
updated logos and index

### PR DESCRIPTION
**Pull request by duduama**

### CODE REVIEW

**Comment by charlesduco** [comment]
You're right. Transparency is better for screen layouts. I'll edit the logos.

**Comment by AbuBaniaz** [comment]
I'm not a fan of making several radio stations show stingraymusic

**Comment by charlesduco** [comment]
I'm open to suggestions. You can always open an issue to fix the problem with stingraymusic.

**Comment by AbuBaniaz** [comment]
Sorry for delayed response,

IMO, we should add logos for the following and correct them. If we cannot find logos for them these entries should be removed.

```
7730_2C1_600_E080000=stingraymusic
alternative=stingraymusic
blues=stingraymusic
classicalgreats=stingraymusic
classicrock=stingraymusic
cooljazz=stingraymusic
feelgoodmusic=stingraymusic
lounge=stingraymusic
rocknrollera=stingraymusic
totalhits=stingraymusic
```

**Pull request merged**
